{% set name = "crick" %}
{% set version = "0.0.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 851bc0802cd4dfb17f8fe99934b224dc355c84de0174ea5d9723b25c7feeb516

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
  host:
    - cython
    - setuptools
    - versioneer
    - python
    - pip
    - numpy
  run:
    - python
    - {{ pin_compatible('numpy') }}

test:
  requires:
    - pytest
  imports:
    - crick
  commands:
    - py.test -v --pyargs crick

about:
  home: https://github.com/jcrist/crick
  license: BSD-3-Clause
  license_file: LICENSE
  summary: 'High performance approximate and streaming algorithms.'

extra:
  recipe-maintainers:
    - jcrist
    - jrbourbeau
    - zklaus
