{% set name = "crick" %}
{% set version = "0.0.5" %}
{% set md5 = "3685332c83499f0120280db77ddf7ccf" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  md5: {{ md5 }}

build:
  number: 1
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - {{ compiler('c') }}
  host:
    - cython
    - setuptools
    - python
    - numpy
  run:
    - python
    - {{ pin_compatible('numpy') }}

test:
  requires:
    - pytest
  imports:
    - crick
  commands:
    - py.test -v --pyargs crick

about:
  home: https://github.com/jcrist/crick
  license: BSD-3-Clause
  license_file: LICENSE
  summary: 'High performance approximate and streaming algorithms.'

extra:
  recipe-maintainers:
    - jcrist
    - jrbourbeau
