{% set name = "crick" %}
{% set version = "0.0.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: bba66d43f64091279a0f7bbab1d49c0b2a7a991eae1ad3f578dcdc2b67fd7a93

build:
  skip: true  # [py<310]
  number: 1
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
  host:
    - cython
    - setuptools
    - versioneer
    - python
    - pip
    - numpy
  run:
    - python
    - numpy

test:
  requires:
    - pytest
  imports:
    - crick
  commands:
    - py.test -v --pyargs crick

about:
  home: https://github.com/jcrist/crick
  license: BSD-3-Clause
  license_file: LICENSE
  summary: 'High performance approximate and streaming algorithms.'

extra:
  recipe-maintainers:
    - MuellerSeb
    - jcrist
    - jrbourbeau
    - zklaus
